import LegalPage from "./LegalPage";

/* ══════════════════════════════════════════════════════════════════════════
   TERMS & CONDITIONS — /terms-and-conditions
   Content-only file rendered by the shared LegalPage.
   ══════════════════════════════════════════════════════════════════════════ */

const SECTIONS = [
  { id: "acceptance-of-terms", title: "Acceptance of terms", body: [
    "These Terms & Conditions govern your use of the IEvalx platform — the website, assessments, AI interviews, job marketplace and employer tools. By creating an account or using the platform you agree to these terms and to our Privacy Policy.",
    "If you are using IEvalx on behalf of a company, you confirm you have authority to bind that company, and “you” includes that company.",
  ]},
  { id: "eligibility-and-accounts", title: "Eligibility & accounts", body: [
    { list: [
      "You must be at least 18 years old and legally able to work or hire in your jurisdiction.",
      "Your account is personal: one account per person, with accurate, current information.",
      "You are responsible for your credentials and for all activity under your account.",
      "Tell us immediately at support@ievalx.com if you suspect unauthorised access.",
    ]},
  ]},
  { id: "assessment-integrity", title: "Assessment & interview integrity", body: [
    "IEvalx exists so that scores mean something. When taking a monitored assessment or interview, you agree not to use unauthorised assistance of any kind — including other people, secondary devices, screen sharing, or AI tools where the assessment prohibits them.",
    { list: [
      "Impersonation — having anyone else take any part of an assessment for you — is prohibited.",
      "Flagged sessions are human-reviewed; confirmed violations invalidate the score.",
      "Repeated or serious violations lead to badge revocation and account termination.",
      "Employers are informed when a result they relied on is invalidated.",
    ]},
  ]},
  { id: "candidate-terms", title: "Candidate terms", body: [
    "Your profile, resume and application answers must be truthful. Verified badges and your CIR score are generated by IEvalx and may not be altered, misrepresented, or displayed outside the platform in a modified form.",
    "Applying to a role shares your profile, relevant results and interview outcomes with that employer. Offers, employment contracts and compensation are strictly between you and the employer — IEvalx is not a party to them.",
  ]},
  { id: "employer-terms", title: "Employer terms", body: [
    { list: [
      "Post only genuine, lawful openings with accurate role, compensation and location details.",
      "Use candidate data solely for evaluating candidates for the posted role.",
      "No discriminatory screening on grounds protected by applicable law.",
      "Respond to candidates through the pipeline — silence-closing applications repeatedly may limit posting privileges.",
    ]},
  ]},
  { id: "plans-and-payments", title: "Plans & payments", body: [
    "Paid plans are billed in advance, monthly or yearly, at the prices shown on the Pricing page at the time of purchase. Taxes are added where applicable.",
    "Plans renew automatically until cancelled; cancelling stops the next renewal and your plan stays active until the end of the paid period. Fees already paid are non-refundable except where the law requires otherwise or a service failure is confirmed by our team.",
  ]},
  { id: "intellectual-property", title: "Intellectual property", body: [
    "The platform — including assessment content, question banks, the CIR methodology, software and branding — belongs to IEvalx and its licensors. You may not copy, scrape, reverse-engineer or resell any part of it.",
    "You retain ownership of the content you upload (resume, answers, recordings) and grant IEvalx a licence to host, process and display it as needed to run the service you asked for.",
  ]},
  { id: "acceptable-use", title: "Acceptable use", body: [
    { list: [
      "No unlawful, fraudulent, or harassing behaviour toward any user.",
      "No automated scraping, bulk data extraction, or probing of our systems.",
      "No uploading of malware or content that infringes someone else's rights.",
      "No circumventing platform fees by moving verified-hire transactions off-platform where a fee applies.",
    ]},
  ]},
  { id: "termination", title: "Suspension & termination", body: [
    "You may delete your account at any time from settings. We may suspend or terminate accounts that violate these terms, compromise assessment integrity, or create legal risk — with notice where practicable.",
    "Sections that by their nature should survive termination (intellectual property, disclaimers, liability limits) survive it.",
  ]},
  { id: "disclaimers-and-liability", title: "Disclaimers & liability", body: [
    "IEvalx is provided “as is”. We verify skills — we do not guarantee that any candidate will be hired or that any role will be filled. To the fullest extent permitted by law, our aggregate liability for any claim is limited to the amounts you paid us in the 12 months before the claim arose.",
  ]},
  { id: "governing-law", title: "Governing law & disputes", body: [
    "These terms are governed by the laws of India. Disputes are subject to the exclusive jurisdiction of the courts of Hyderabad, Telangana, after a good-faith attempt to resolve the matter with our support team first.",
  ]},
  { id: "changes-to-terms", title: "Changes to these terms", body: [
    "We may update these terms as the platform evolves. Material changes are announced in-app and by email at least 14 days before taking effect; continuing to use IEvalx after that date means you accept the updated terms.",
  ]},
];

export default function TermsPage() {
  return (
    <LegalPage
      eyebrow="Terms & Conditions"
      title="The Rules That Keep Scores Honest"
      subtitle="Plain-language terms for candidates and employers — what you can expect from IEvalx, and what we expect from you."
      updated="1 July 2026"
      sections={SECTIONS}
    />
  );
}